<style type="text/css">
    
    #pnlGerenciador{
        margin-left: 10%;
        margin-top: 20px;
        background-color: black; 
        color: white; 
        width: 80%; 
        height: 500px; 
        overflow-y: scroll;
    }

</style>

<legend>Gerenciador</legend>

<h1>Gerenciador de Sites</h1>


    <button id="btn-iniciar-gerenciador" type="button" class="btn btn-default" >Iniciar Gerenciador</button>

    <div id='pnlGerenciador' ></div>

<script>

function dataAtualFormatada(){
    var data = new Date();
    var dia = data.getDate();
    if (dia.toString().length == 1)
      dia = "0"+dia;
    var mes = data.getMonth()+1;
    if (mes.toString().length == 1)
      mes = "0"+mes;
    var ano = data.getFullYear();  
    return dia+"-"+mes+"-"+ano;
}

function atualizaLogGerenciador(){



    $.ajax({

        url : '/BufferGerenciadorPaginas-'+dataAtualFormatada()+'.txt',
        dataType : 'text',
        success: function(data){

            $('#pnlGerenciador').html(data);
            var pnlGerenciador = document.getElementById("pnlGerenciador");
            pnlGerenciador.scrollTop = pnlGerenciador.scrollHeight;
            setTimeout('atualizaLogGerenciador()', 500);
        }
    })


}

$(document).ready(function(){

    $('#btn-iniciar-gerenciador').click(function(element){
        $.ajax({
            url: "/cmdgerenciador",
            async : true,
            beforeSend : function(){
                $('#btn-iniciar-gerenciador').html('Executando ...<div class="three-quarters-loader">Loading</div>');
            },
            success: function (retorno) {
                $('#btn-iniciar-gerenciador').html('Iniciar Gerenciador');
                //$('#btn-iniciar-gerenciador').click();
                atualizaLogGerenciador();
            },
            error: function (retorno) {
                $('#btn-iniciar-gerenciador').html('Iniciar Gerenciador');
                //$('#btn-iniciar-gerenciador').click();
            }
        })
    });

    atualizaLogGerenciador();

})


</script>
