<h2>Notificações</h2>
<hr />
<form class="form-inline" method="post" action="#">
    <fieldset>
        <legend><span class="glyphicon glyphicon-filter" ></span> Filtro</legend>
        <div class="form-group">
            <label for="notificacoes-data">Data Referência: </label>
            <input type="data" class="form-control" id="notificacoes-data" placeholder="__/__/____">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-refresh" ></span></button>
    </fieldset>
</form>

<table class="table">
    
</table>