<?php
	foreach ($this->view->badgeNaoVistas as $notificacao){
		$badgeNotificado = $notificacao[badge];
	}

	foreach ($this->view->badgeVistas as $notificacao){
		$badgeAcessado = $notificacao[badge];
	}
?>
<script>
	function atualizaNotificacao(notificacaoid){
		/*
		* atualiza com ajax o dtClick na tabela de notificacao
		*/
		$.ajax({
			type: "POST",
			url: "/notificacao/atualiza/pagina",
			data:{ 
				notificacao: notificacaoid
			},
			success: function (retorno){
				location.reload();
			}
		})
	}
</script>

<form class="form-inline" method="post" action="#">
    <fieldset>
        <legend><span class="glyphicon glyphicon-filter" ></span> Filtro</legend>
        <div class="form-group">
            <label for="notificacoes-data">Data Referência: </label>
            <input type="data" class="form-control dateInput" id="dtFiltroJornalEdital" placeholder="__/__/____" name="dtFiltroJornalEdital" value="<?php echo $_POST[dtFiltroJornalEdital] ?>">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-refresh" ></span></button>
    </fieldset>
</form>
<hr />

<div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Jornais | Editais notificados <span class="badge" ><?php echo $badgeNotificado; ?></span> </a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Jornais | Editais acessados <span class="badge" ><?php echo $badgeAcessado; ?></span></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                    </tr>
                </thead>
                <tbody>
                	<?php
                		
                		foreach ($this->view->notificacoesNaoVistas as $notificacao):
                	?>
                		<tr>
                			<td><?php echo $notificacao[notificacaoid]?></td>
                			<td><?php echo $notificacao[descricao]?></td>
                			<td>
	                			<a href="<?php echo $notificacao[link]?>" target="_blank" onclick="atualizaNotificacao(<?php echo $notificacao[notificacaoid]?>);"><?php echo $notificacao[link]?></a>
                			</td>
                			<td><?php echo $notificacao[palavraencontrada]?></td>
                			<td><?php echo $notificacao[data]?></td>
                			<td><?php echo $notificacao[hora]?></td>
                		</tr>
					<?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                        <th>Data Clique</th>
                    </tr>
                </thead>
                <tbody>
                	<?php
                		
                		foreach ($this->view->notificacoesVistas as $notificacao):
                	?>
                		<tr>
                			<td><?php echo $notificacao[notificacaoid]?></td>
                			<td><?php echo $notificacao[descricao]?></td>
                			<td><a href="<?php echo $notificacao[link]?>" target="_blank"><?php echo $notificacao[link]?></a></td>
                			<td><?php echo $notificacao[palavraencontrada]?></td>
                			<td><?php echo $notificacao[data]?></td>
                			<td><?php echo $notificacao[hora]?></td>
                			<td><?php echo $notificacao[dtclick]?></td>
                			<td></td>
                		</tr>
					<?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            e.target // newly activated tab
            e.relatedTarget // previous active tab
        })
    });

	/* Máscaras */
	jQuery(function($){
		$(".dateInput").mask("99/99/9999");

	})
</script>