<form class="form-inline" method="post" action="#">
    <fieldset>
        <legend><span class="glyphicon glyphicon-filter" ></span> Filtro</legend>
        <div class="form-group">
            <label for="notificacoes-data">Data Referência: </label>
            <input type="data" class="form-control" id="notificacoes-data" placeholder="__/__/____">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-refresh" ></span></button>
    </fieldset>
</form>
<hr />



<div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Jornais | Editais notificados <span class="badge" >2</span> </a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Jornais | Editais acessados <span class="badge" >2</span></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>Example</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>s/p</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>s/p</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                    </tr>

                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                        <th>Data Clique</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>Example</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                        <td>07/03/2015</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>s/p</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                        <td>07/03/2015</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Site Teste</td>
                        <td><a target="_blank" href="http://www.example.com">www.example.com</a></td>
                        <td>s/p</td>
                        <td>06/03/2015</td>
                        <td>23:01:32</td>
                        <td>07/03/2015</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            e.target // newly activated tab
            e.relatedTarget // previous active tab
        })
    });
</script>