<?php
    if(is_array($this->view->badgeNaoVistas)){
        foreach ($this->view->badgeNaoVistas as $notificacao){
            $badgeNotificado = $notificacao[badge];
        }
    }

    if(is_array($this->view->badgeVistas)){
        foreach ($this->view->badgeVistas as $notificacao){
            $badgeAcessado = $notificacao[badge];
        }
    }

?>
<script>

    $(document).ready(function(){
        $('#chk-checkTodos').click(function(){
            selecionarTodosCheckBox();
        })

        $('#btn-notificarpaginas').click(function(){
            notificarPaginas();
        });
    });

    function notificarPaginas(){
        if(confirm("Deseja Notificar as páginas selecionadas ?")){
            var checks = $('input[type=checkbox]:checked');
            var count = checks.length;
            
            if(checks[0] == undefined){

                alert('Para executar a ação selecione pelo menos um registro');
                return;

            }


            $.each(checks, function(key, value){

                $.ajax({
                    type: "POST",
                    url: "/notificacao/atualiza/pagina",
                    data:{
                        notificacao: $(value).val()
                    },
                    success: function (retorno){
                    }
                })

            })

            if(!--count){
                setTimeout(function(){ location.reload(); }, 3000);
            }

        }

    }

    function selecionarTodosCheckBox(){

        var checks = $('input[type=checkbox]');

        if($('#chk-checkTodos').is(':checked')){

            $.each(checks, function(key, value){
                $(value).prop('checked',true);
            });

            return;
        }

        $.each(checks, function(key, value){
            $(value).prop('checked',false);
        });

        return;

    }

	function atualizaNotificacao(notificacaoid){
		/*
		* atualiza com ajax o dtClick na tabela de notificacao
		*/
		$.ajax({
			type: "POST",
			url: "/notificacao/atualiza/pagina",
			data:{ 
				notificacao: notificacaoid
			},
			success: function (retorno){
				location.reload();
			}
		})
	}
</script>

<form class="form-inline" method="post" action="#">
    <fieldset>
        <legend><span class="glyphicon glyphicon-filter" ></span> Filtro</legend>
        <div class="form-group">
            <label for="notificacoes-data">Data Referência: </label>
            <input type="data" class="form-control dateInput" id="dtFiltroJornalEdital" placeholder="__/__/____" name="dtFiltroJornalEdital" value="<?php echo $_POST[dtFiltroJornalEdital] ?>">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-refresh" ></span></button>
    </fieldset>
</form>
<hr />

<fieldset>
    <legend><span class="glyphicon glyphicon-cog" ></span> Ações </legend>
    <div class="form-group" >
        <button id="btn-notificarpaginas" type="button" class="btn btn-primary" >Notificar Jornais | Editais selecionados</button>
    </div>
</fieldset>
<hr>

<div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Jornais | Editais notificados <span class="badge" ><?php echo $badgeNotificado; ?></span> </a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Jornais | Editais acessados <span class="badge" ><?php echo $badgeAcessado; ?></span></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
            <table class="table" id="table1">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="chk-checkTodos" /></th>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                    </tr>
                </thead>
                <tbody>
                	<?php
                		if(is_array($this->view->notificacoesNaoVistas)) {


                            foreach ($this->view->notificacoesNaoVistas as $notificacao):

                                ?>
                                <tr>
                                    <td><input type="checkbox" value="<?php echo $notificacao[notificacaoid]; ?>"/></td>
                                    <td><?php echo $notificacao[notificacaoid] ?></td>
                                    <td><?php echo $notificacao[descricao] ?></td>
                                    <td>
                                        <a href="<?php echo $notificacao[link] ?>" target="_blank"
                                           onclick="atualizaNotificacao(<?php echo $notificacao[notificacaoid] ?>);"><?php echo $notificacao[link] ?></a>
                                    </td>
                                    <td><?php echo $notificacao[palavraencontrada] ?></td>
                                    <td><?php echo $notificacao[data] ?></td>
                                    <td><?php echo $notificacao[hora] ?></td>
                                </tr>
                                <?php
                            endforeach;
                        }
                    ?>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="profile">
            <table class="table" id="table1">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Descrição</th>
                        <th>Link</th>
                        <th>Palavra encontrada</th>
                        <th>Data</th>
                        <th>Hora</th>
                        <th>Data Clique</th>
                    </tr>
                </thead>
                <tbody>
                	<?php
                		if(is_array($this->view->notificacoesVistas)) {
                            foreach ($this->view->notificacoesVistas as $notificacao):


                                ?>
                                <tr>
                                    <td><?php echo $notificacao[notificacaoid] ?></td>
                                    <td><?php echo $notificacao[descricao] ?></td>
                                    <td><a href="<?php echo $notificacao[link] ?>"
                                           target="_blank"><?php echo $notificacao[link] ?></a></td>
                                    <td><?php echo $notificacao[palavraencontrada] ?></td>
                                    <td><?php echo date('d/m/Y', strtotime($notificacao[data])) ?></td>
                                    <td><?php echo $notificacao[hora] ?></td>
                                    <td><?php echo date('d/m/Y', strtotime($notificacao[dtclick])); ?></td>
                                </tr>
                                <?php
                            endforeach;
                        }
                    ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            e.target // newly activated tab
            e.relatedTarget // previous active tab
        })
    });
</script>