<h2>Bem-Vindo ao BkdWeb!</h2>
<h4><small>Sistema de Pesquisa em sites</small></h4>
<hr />
<div>
<?php
/*$ch = curl_init();
$timeout = 0;
curl_setopt($ch, CURLOPT_URL, 'www.terra.com');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
$conteudo = curl_exec ($ch);
curl_close($ch);

 //preg_match_all('(Example)', $conteudo, $conteudo2);
$conteudo2 = str_replace('Notícias', '<div class="alert alert-success" role="alert">Notícias</div>', strip_tags($conteudo));

/*echo '<pre>';
var_dump($conteudo2);
echo '</pre>';
*/
?>
</div>