<?php //var_dump($_SESSION); ?>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"></span> BkdWEB </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <span class="glyphicon glyphicon-pencil"></span> 
                        Cadastros
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/pagina"><span class="glyphicon glyphicon-folder-open"></span> Páginas</a></li>
                        <li><a href="/jornaiseditais"><span class="glyphicon glyphicon-folder-open"></span> Jornais | Editais</a></li>
                    </ul>
                </li>
                <li><a href="/notificacoes-paginas">Notificações Páginas <span class="badge" >4</span></a></li>
                <li><a href="/notificacoes-jornais-editais">Notificações Jornais | Editais <span class="badge" >4</span></a></li>
                <?php
                	//valida se o usuario que esta logado e do tipo administrador(1) para mostrar o menu de relatorios
                	if($_SESSION[tipoUsuarioId] == 1){
                ?>
                		<li><a href="/relatorio"><span class="glyphicon glyphicon-list-alt"></span> Relatórios</a></li>
                        <li><a href="/gerenciador"><span class="glyphicon glyphicon-user"></span> Iniciar Gerenciador</a></li>
                <?php
                	}//endIf
                ?>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout"><span class="glyphicon glyphicon-ban-circle"></span> Logout </a></li>
            </ul>
        </div>

    </div>
</nav>