<pre>
<?php
var_dump($this->paginas);
?>
</pre>
<form class="form-horizontal" action="/pagina/add" method="post" >
    <fieldset>

        <!-- Form Name -->
        <legend>Cadastro de Páginas</legend>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">ID</label>  
            <div class="col-md-4">
                <input readonly="" id="pagina-id" name="pagina[paginaid]"  class="form-control input-md" type="text">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Descrição:</label>  
            <div class="col-md-4">
                <input id="pagina-descricao" name="pagina[descricao]"  class="form-control input-md" type="text">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Link:</label>  
            <div class="col-md-4">
                <input id="pagina-link" name="pagina[link]"  class="form-control input-md" type="text">

            </div>
        </div>

        <!-- Text input-->
        <!--<div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Refresh:</label>  
            <div class="col-md-4">
                <input id="pagina-refresh" name="pagina[reload]"  class="form-control input-md" type="text">

            </div>
        </div>
        -->
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Busca:</label>  
            <div class="col-md-4">
                <input id="pagina-busca" name="pagina[busca]"  class="form-control input-md" type="text">

            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for=""></label>
            <div class="col-md-4">
                <button id="" name="" class="btn btn-success pull-right ">Salvar</button>
            </div>
        </div>
        
        <!-- Hiddens -->    
        <input type="hidden" name="tipopagina" value="P" />

    </fieldset>
</form>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Descrição</th>
            <th>Link</th>
            <!--<th>Refresh</th>-->
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->paginas as $pagina): ?>
        <tr>
            <td><?php echo $pagina->getPaginaId(); ?></td>
            <td><?php echo $pagina->getDescricao(); ?></td>
            <td><?php echo $pagina->getLink(); ?></td>
            <td colspan="2">
                <a class="btn btn-default btn-lg" href="/pagina?paginaId=<?php echo $pagina->getPaginaId(); ?>" ><span class="glyphicon glyphicon-pencil" ></span></a>
            </td>
        </tr>
        <?php endforeach ?>
        <!--<tr>
            <td>1</td>
            <td>Site 1</td>
            <td>www.teste.com.br</td>
            <td colspan="2" >
                <button class="btn btn-default btn-lg" ><span class="glyphicon glyphicon-pencil" ></span></button>
                <button class="btn btn-danger btn-lg " ><span class="glyphicon glyphicon-remove" ></span></button>
            </td>
        </tr>
        <tr>
            <td>1</td>
            <td>Site 1</td>
            <td>www.teste.com.br</td>
            <td colspan="2" >
                <button class="btn btn-default btn-lg" ><span class="glyphicon glyphicon-pencil" ></span></button>
                <button class="btn btn-danger btn-lg " ><span class="glyphicon glyphicon-remove" ></span></button>
            </td>
        </tr>
        <tr>
            <td>1</td>
            <td>Site 1</td>
            <td>www.teste.com.br</td>
            <td colspan="2" >
                <button class="btn btn-default btn-lg" ><span class="glyphicon glyphicon-pencil" ></span></button>
                <button class="btn btn-danger btn-lg " ><span class="glyphicon glyphicon-remove" ></span></button>
            </td>
        </tr>
        <tr>
            <td>1</td>
            <td>Site 1</td>
            <td>www.teste.com.br</td>
            <td colspan="2" >
                <button class="btn btn-default btn-lg" ><span class="glyphicon glyphicon-pencil" ></span></button>
                <button class="btn btn-danger btn-lg " ><span class="glyphicon glyphicon-remove" ></span></button>
            </td>
        </tr>-->
    </tbody>
    
</table>
